title: case 
author:
    name: case
    email: case0x01@protonmail.com

show_excerpts: false 

minima:
    date_format: "%b %-d, %Y"

    social_links:
        twitter: onlycase_
        github: onlycase




# Build settings
theme: minima
plugins:
     - jekyll-feed
     - jekyll-seo-tag

header_pages:
    - index.md
    - tags/projects/index.md
    - tags/worldbuilding/index.md 

minima:
    skin: dark
